apiVersion: apps/v1
kind: Deployment

metadata:
  name: cpu-stress
  namespace: exercise-06

spec:
  replicas: 2

  selector:
    matchLabels:
      app: cpu-stress

  template:
    metadata:
      labels:
        app: cpu-stress

    spec:
      containers:
        - name: nginx
          image: nginx:1.27

          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"

            limits:
              cpu: "1000m"
              memory: "512Mi"

          ports:
            - containerPort: 80
