apiVersion: v1
kind: Service

metadata:
  name: checkout-service
  namespace: observability-app

  labels:
    app: checkout-service

spec:
  selector:
    app: checkout-service

  ports:
  - name: http
    port: 5000
    targetPort: 5000

  type: ClusterIP
