apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: observability-services
  namespace: observability

  labels:
    release: monitoring

spec:
  namespaceSelector:
    matchNames:
      - observability-app

  selector:
    matchExpressions:
      - key: app
        operator: Exists

  endpoints:
    - port: http
      path: /metrics
      interval: 15s
