apiVersion: apps/v1
kind: Deployment

metadata:
  name: payment-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: payment-service

  template:
    metadata:
      labels:
        app: payment-service

    spec:
      containers:
      - name: payment-service

        image: payment-service:v1

        imagePullPolicy: Never

        ports:
        - containerPort: 5000

        env:

        - name: DB_HOST
          value: postgres

        - name: DB_PORT
          value: "5432"

        - name: DB_NAME
          value: payments

        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
