apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-secret-sync
spec:
  refreshInterval: 1m

  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore

  target:
    name: app-secret-k8s

  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: app-secret
        property: DB_USERNAME

    - secretKey: DB_PASSWORD
      remoteRef:
        key: app-secret
        property: DB_PASSWORD

    - secretKey: JWT_SECRET
      remoteRef:
        key: app-secret
        property: JWT_SECRET
